### ISSUE TITLE
Only for Adobe Illustrator CC ?

### ISSUE THREAD

**Issue by thiphariel** [davidderaedt/SVG-NOW#1]
Hi.

Is this extension available only for Illustrator CC ? I got an error while trying to install on CS6...

Thanks for pointing me out

**Comment by davidderaedt** [comment]
Hi

Yes, CC only

David Deraedt - Creative Cloud Consultant - Adobe Systems France

On 1 avr. 2015, at 11:09, Thco <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi.

Is this extension available only for Illustrator CC ? I got an error while trying to install on CS6...

Thanks for pointing me out

**Comment by thiphariel** [comment]
Ok thanks... too bad :(

I close.
